services:
  app:
    container_name: app
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/node/app

  db:
    container_name: db
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
